services:
  - type: web
    name: fruit-porter-shop
    runtime: node
    plan: free
    rootDir: fruit-shop/backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
