services:
  - type: web
    name: fruit-porter
    runtime: node
    rootDir: fruit-shop/backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.18.0
